export const category = {
  0: "カスタム",
  1: "画風",
  2: "ポーズ",
  3: "ポーズ(オプション)",
  4: "アートスタイル",
  5: "感情・表情",
  6: "胸囲",
  7: "視線",
  8: "射精",
  9: "身体的特徴",
  10: "性行為",
  11: "体型",
  12: "等身",
  13: "髪型",
  14: "髪色",
  15: "服装",
  16: "服装(オプション)",
  17: "目の色",
  18: "画角",
  19: "エフェクト",
  20: "人数",
}

export const presetData = {
  1: {category: 4, label: "FF11", value: "final fantasy xi"},
  2: {category: 4, label: "アークナイツ", value: "arknights"},
  3: {category: 4, label: "アイマス（初代）", value: "idol master"},
  4: {category: 4, label: "アズレン", value: "azur lane"},
  5: {category: 4, label: "アマガミ", value: "amagami"},
  6: {category: 4, label: "グラブル", value: "granblue fantasy"},
  7: {category: 4, label: "ゴチうさ", value: "gochiusa"},
  8: {category: 4, label: "サイゲ", value: "cygames"},
  9: {category: 4, label: "ディスガイア", value: "disgaea"},
  10: {category: 4, label: "ペルソナ5", value: "persona5"},
  11: {category: 4, label: "ラブライブ！", value: "love live!"},
  12: {category: 4, label: "京アニ", value: "kyoto animation"},
  13: {category: 4, label: "原神", value: "genshin impact"},
  14: {category: 19, label: "xxxから血が出る", value: "blood from xxx"},
  15: {category: 19, label: "ふきだしハテナ", value: "spoken question mark"},
  16: {category: 19, label: "ふきだし音符", value: "spoken musical note"},
  17: {category: 19, label: "移動線", value: "motion lines"},
  18: {category: 19, label: "影絵にする", value: "silhouette"},
  19: {category: 19, label: "汗をかく", value: "perspired"},
  20: {category: 19, label: "汗を大量にかく", value: "sweaty"},
  21: {category: 19, label: "強い湯気", value: "fog"},
  22: {category: 19, label: "集中線", value: "emphasis lines"},
  23: {category: 19, label: "少し汗をかく", value: "very humid"},
  24: {category: 19, label: "息切れ", value: "be breathless"},
  25: {category: 19, label: "体から湯気", value: "steaming body"},
  26: {category: 19, label: "湯気", value: "steam"},
  27: {category: 19, label: "平面化（強くすると塗りが平らになりアニメ風）", value: "outlined vector graphics"},
  28: {category: 2, label: "～の上に座る", value: "sitting on"},
  29: {category: 2, label: "I字立ち", value: "standing split legs"},
  30: {category: 2, label: "jack-o-チャレンジ", value: "top down bottom up"},
  31: {category: 2, label: "いちゃつく", value: "flirt"},
  32: {category: 2, label: "うつ伏せ", value: "lying on stomach"},
  33: {category: 2, label: "おっぱいをくっつける", value: "trait connection"},
  34: {category: 2, label: "お互いに強く抱きつく", value: "hug each other tight"},
  35: {category: 2, label: "お尻を突き出す", value: "doggystyle"},
  36: {category: 2, label: "しゃがみ込み", value: "squatting"},
  37: {category: 2, label: "テーブルに胸を乗せる", value: "breasts on table"},
  38: {category: 2, label: "ナチュラルな立ち姿", value: "contrapposto"},
  39: {category: 2, label: "のけぞり", value: "arched back"},
  40: {category: 2, label: "ファイティングポーズ", value: "fighting stance"},
  41: {category: 2, label: "横寝", value: "lying on side"},
  42: {category: 2, label: "何かに胸を乗せている", value: "breast rest"},
  43: {category: 2, label: "開脚", value: "spread legs"},
  44: {category: 2, label: "顔合わせ", value: "face to face"},
  45: {category: 2, label: "仰向け", value: "lying on back"},
  46: {category: 2, label: "胡坐", value: "indian style"},
  47: {category: 2, label: "後ろから抱きつく", value: "hug from behind"},
  48: {category: 2, label: "座っている", value: "sitting"},
  49: {category: 2, label: "四つん這い", value: "all fours"},
  50: {category: 2, label: "指を口に当てる", value: "finger to mouth"},
  51: {category: 2, label: "指を頬に当てる", value: "finger to cheek"},
  52: {category: 2, label: "自撮り", value: "selfie"},
  53: {category: 2, label: "手を握る", value: "holding hands"},
  54: {category: 2, label: "首をかしげる", value: "tilting head"},
  55: {category: 2, label: "女の子座り", value: "wariza"},
  56: {category: 2, label: "女の子同士のキス1", value: "2girls kiss"},
  57: {category: 2, label: "女の子同士のキス2", value: "a girl kissing a girl"},
  58: {category: 2, label: "寝そべり", value: "lying"},
  59: {category: 2, label: "振り向き", value: "turning around"},
  60: {category: 2, label: "振り向き１", value: "looking back, from behind, looking at camera"},
  61: {category: 2, label: "振り向き２", value: "looking back, from behind, looking at viewer"},
  62: {category: 2, label: "正座", value: "seiza"},
  63: {category: 2, label: "走っている姿", value: "running"},
  64: {category: 2, label: "足を閉じる", value: "knees together feet apart"},
  65: {category: 2, label: "足組み", value: "crossed legs"},
  66: {category: 2, label: "着座のふともも", value: "sitting thighhighs"},
  67: {category: 2, label: "土下座", value: "prostration"},
  68: {category: 2, label: "乳合わせ（ガッツリ合わせる）", value: "symmetrical docking"},
  69: {category: 2, label: "馬乗り", value: "sit astride"},
  70: {category: 2, label: "膝抱え１", value: "hold up knee"},
  71: {category: 2, label: "膝抱え２", value: "hugging own legs"},
  72: {category: 2, label: "膝枕", value: "lying on lap"},
  73: {category: 2, label: "膝立ち", value: "kneeling"},
  74: {category: 2, label: "歩き", value: "walking"},
  75: {category: 2, label: "抱きしめる", value: "embrace each other"},
  76: {category: 2, label: "抱きまくら紹介構図", value: "dakimakura"},
  77: {category: 2, label: "頬をくっつける", value: "touch each other's lips face to face"},
  78: {category: 2, label: "立ち姿", value: "standing"},
  79: {category: 2, label: "立った状態で少し開脚", value: "legs apart"},
  80: {category: 2, label: "脇", value: "armpit"},
  81: {category: 2, label: "腕上げ", value: "arms up"},
  82: {category: 2, label: "蹲踞", value: "crouching"},
  83: {category: 3, label: "xxxに入った状態", value: "in container xxx"},
  84: {category: 3, label: "あててんのよ", value: "breast press"},
  85: {category: 3, label: "うなじ", value: "nape"},
  86: {category: 3, label: "おしっこ1", value: "peeing"},
  87: {category: 3, label: "おしっこ2", value: "have to pee"},
  88: {category: 3, label: "がおがおポーズ", value: "claw pose"},
  89: {category: 3, label: "ガラス越し", value: "through glass"},
  90: {category: 3, label: "たくし上げ", value: "lifted by self"},
  91: {category: 3, label: "たくし上げ（シャツ）", value: "shirt lift"},
  92: {category: 3, label: "たくし上げ（スカート）", value: "skirt lift"},
  93: {category: 3, label: "たくし上げ（セーター）", value: "sweater lift"},
  94: {category: 3, label: "たくし上げ（衣服）", value: "clothes lift"},
  95: {category: 3, label: "ダブルピース", value: "double v"},
  96: {category: 3, label: "ラーメンを咥える", value: "blowing ramen out of her mouth"},
  97: {category: 3, label: "愛液", value: "pussy juice"},
  98: {category: 3, label: "開口", value: "open mouth"},
  99: {category: 3, label: "顔に手を突く", value: "hand on own face"},
  100: {category: 3, label: "肩甲骨（背中）", value: "shoulder blades"},
  101: {category: 3, label: "股下の三角形", value: "thigh gap"},
  102: {category: 3, label: "拘束", value: "restrained"},
  103: {category: 3, label: "荒縄縛り", value: "shibari"},
  104: {category: 3, label: "手を足にかける", value: "hand between legs"},
  105: {category: 3, label: "深く前かがみ", value: "bent over"},
  106: {category: 3, label: "水に少し浸かった状態", value: "wading"},
  107: {category: 3, label: "水に多く浸かった状態", value: "partially submerged"},
  108: {category: 3, label: "水に浮かぶ", value: "afloat"},
  109: {category: 3, label: "睡眠", value: "sleeping"},
  110: {category: 3, label: "舌出し", value: "tongue out"},
  111: {category: 3, label: "前かがみ", value: "leaning forward"},
  112: {category: 3, label: "足裏", value: "soles"},
  113: {category: 3, label: "乳輪チラリ", value: "areola slip"},
  114: {category: 3, label: "閉口", value: "closed mouth"},
  115: {category: 3, label: "立ち絵", value: "tachi-e"},
  116: {category: 18, label: "パノラマ", value: "panorama"},
  117: {category: 18, label: "横から", value: "from side"},
  118: {category: 18, label: "下から", value: "from below"},
  119: {category: 18, label: "魚眼", value: "fisheye"},
  120: {category: 18, label: "胸から頭まで", value: "upper body"},
  121: {category: 18, label: "後ろから", value: "from behind"},
  122: {category: 18, label: "主に顔、たまに胸までのアップ", value: "portrait"},
  123: {category: 18, label: "小人視点（パースが強くなる）", value: "foreshortening"},
  124: {category: 18, label: "上から", value: "from above"},
  125: {category: 18, label: "全身", value: "full body"},
  126: {category: 18, label: "全体表示（横長）", value: "game cg, dutch angle"},
  127: {category: 1, label: "スケッチ", value: "sketch"},
  128: {category: 1, label: "ピクセル風", value: "pixel art"},
  129: {category: 1, label: "モノクロラフ", value: "monochrome rough sketch"},
  130: {category: 1, label: "鉛筆描き", value: "crosshatching"},
  131: {category: 1, label: "厚い輪郭", value: "thick outline"},
  132: {category: 1, label: "黒い輪郭", value: "black outline"},
  133: {category: 1, label: "黒鉛", value: "graphite"},
  134: {category: 1, label: "主線なし", value: "no lineart"},
  135: {category: 1, label: "色鉛筆", value: "colored pencil"},
  136: {category: 1, label: "水彩", value: "watercolor"},
  137: {category: 1, label: "線画", value: "lineart"},
  138: {category: 1, label: "描き込み増し", value: "detailed and intricate"},
  139: {category: 1, label: "油彩", value: "oil painting"},
  140: {category: 5, label: "（痛みや嫌悪、不快感で）眉をひそめる", value: "grimace"},
  141: {category: 5, label: "（独善的な）にやにや 片方の口角が上がっている", value: "smirk"},
  142: {category: 5, label: "（不意にロマンチックな状況になって）慌てる顔", value: "flustered"},
  143: {category: 5, label: "V字眉（ ＼ ／ こういう眉）", value: "v-shaped eyebrows"},
  144: {category: 5, label: "アヘ顔", value: "ahegao"},
  145: {category: 5, label: "イライラ", value: "annoyed"},
  146: {category: 5, label: "うつ", value: "depressed"},
  147: {category: 5, label: "キューブリックの凝視", value: "kubrick stare"},
  148: {category: 5, label: "ショックや絶望などでモノクロになること", value: "color drain"},
  149: {category: 5, label: "シリアス、深刻な表情", value: "serious"},
  150: {category: 5, label: "すすり泣く", value: "sobbing"},
  151: {category: 5, label: "ため息", value: "sigh"},
  152: {category: 5, label: "ドヤ顔", value: "doyagao, self-satisfaction, smugness"},
  153: {category: 5, label: "ナーバス、緊張", value: "nervous"},
  154: {category: 5, label: "にやにや", value: "grin"},
  155: {category: 5, label: "パニック、慌てる", value: "panicking"},
  156: {category: 5, label: "ふくれっ面", value: "pout"},
  157: {category: 5, label: "レイプ顔", value: "rape face"},
  158: {category: 5, label: "レイプ目", value: "empty eyes"},
  159: {category: 5, label: "押し殺した笑い、笑いをこらえる", value: "stifled laugh"},
  160: {category: 5, label: "顔に手を置く。やれやれ顔", value: "facepalm"},
  161: {category: 5, label: "顔に置く", value: "hand_on_own_face"},
  162: {category: 5, label: "顔全体の赤面", value: "full-face blush"},
  163: {category: 5, label: "泣く", value: "crying"},
  164: {category: 5, label: "泣く（目を開いて）", value: "crying with eyes open"},
  165: {category: 5, label: "強制的な笑顔（作り笑い？）", value: "forced smile"},
  166: {category: 5, label: "恐ろしい", value: "horrified"},
  167: {category: 5, label: "恐怖、痛み、苦痛で眉をひそめる、ひるむ", value: "wince"},
  168: {category: 5, label: "驚いた顔", value: "surprised"},
  169: {category: 5, label: "軽い笑顔（モナリザのような）ほほえみ", value: "light smile"},
  170: {category: 5, label: "軽蔑", value: "disdain"},
  171: {category: 5, label: "決心した表情、決め顔", value: "determined"},
  172: {category: 5, label: "嫌悪", value: "disgust"},
  173: {category: 5, label: "口を開ける", value: "open mouth"},
  174: {category: 5, label: "口角が切り裂かれた笑顔", value: "glasgow smile"},
  175: {category: 5, label: "幸せな表情", value: "happy"},
  176: {category: 5, label: "考える顔", value: "thinking"},
  177: {category: 5, label: "混乱した表情", value: "confused"},
  178: {category: 5, label: "罪悪感", value: "guilt"},
  179: {category: 5, label: "指で口角を上げる笑顔", value: "fingersmile"},
  180: {category: 5, label: "歯を食いしばる", value: "clenched teeth"},
  181: {category: 5, label: "失望した、呆れ顔", value: "disappointed"},
  182: {category: 5, label: "邪悪なにやにや", value: "evil grin"},
  183: {category: 5, label: "邪悪な笑顔", value: "evil smile"},
  184: {category: 5, label: "邪悪な表情、悪だくみ", value: "evil"},
  185: {category: 5, label: "寂しい、孤独", value: "lonely"},
  186: {category: 5, label: "笑顔", value: "smile"},
  187: {category: 5, label: "上向きの目（アヘ顔）", value: "rolling eyes"},
  188: {category: 5, label: "心配する", value: "worried"},
  189: {category: 5, label: "震える", value: "trembling"},
  190: {category: 5, label: "酔っ払い、お酒に酔った顔", value: "drunk"},
  191: {category: 5, label: "青ざめる", value: "turn pale"},
  192: {category: 5, label: "絶叫　叫ぶ", value: "screaming"},
  193: {category: 5, label: "絶頂", value: "orgasm"},
  194: {category: 5, label: "絶望", value: "despair"},
  195: {category: 5, label: "楕円形の頬", value: "blush stickers"},
  196: {category: 5, label: "退屈そうな表情", value: "bored"},
  197: {category: 5, label: "恥ずかしい", value: "embarrassed"},
  198: {category: 5, label: "痛みの表情", value: "pain"},
  199: {category: 5, label: "妬みの表情、嫉妬", value: "envy"},
  200: {category: 5, label: "怒り", value: "angry"},
  201: {category: 5, label: "怒りマーク💢、青筋", value: "anger vein"},
  202: {category: 5, label: "動揺する", value: "upset"},
  203: {category: 5, label: "独善的 前で腕を組むようなドヤ顔　お嬢様のような…", value: "smug"},
  204: {category: 5, label: "波状の口", value: "wavy mouth"},
  205: {category: 5, label: "悲しい", value: "sad"},
  206: {category: 5, label: "悲しみで眉をひそめる", value: "frown"},
  207: {category: 5, label: "悲しみの笑顔", value: "sad smile"},
  208: {category: 5, label: "疲れた表情", value: "tired"},
  209: {category: 5, label: "眉間にしわ", value: "furrowed brow"},
  210: {category: 5, label: "鼻の上を赤らめる", value: "nose blush"},
  211: {category: 5, label: "鼻血を流す", value: "nosebleed"},
  212: {category: 5, label: "病んだ笑顔", value: "crazy smile"},
  213: {category: 5, label: "病んでいる表情", value: "crazy"},
  214: {category: 5, label: "不満な表情 欲求不満", value: "frustrated"},
  215: {category: 5, label: "怖がる", value: "scared"},
  216: {category: 5, label: "物思いに耽る", value: "pensive"},
  217: {category: 5, label: "片眉を上げた表情", value: "raised eyebrow"},
  218: {category: 5, label: "片目を閉じる（ウインク）", value: "one eye closed (winking)"},
  219: {category: 5, label: "頬に当てる", value: "hand_on_own_cheek"},
  220: {category: 5, label: "頬染め", value: "blush"},
  221: {category: 5, label: "漫画的なびっくり表現", value: "^^^"},
  222: {category: 5, label: "魅惑的な笑顔", value: "seductive smile"},
  223: {category: 5, label: "眠い表情", value: "sleepy"},
  224: {category: 5, label: "無表情、真顔", value: "expressionless"},
  225: {category: 5, label: "目を閉じた顔", value: "closed eyes"},
  226: {category: 5, label: "憂鬱な表情", value: "gloom (expression)"},
  227: {category: 5, label: "離れた唇", value: "parted lips"},
  228: {category: 5, label: "涙をながす", value: "tears"},
  229: {category: 5, label: "涙目", value: "water eye"},
  230: {category: 5, label: "嘲る顔？　嘲笑？", value: "troll face"},
  231: {category: 5, label: "拗ねた顔", value: "sulking"},
  232: {category: 5, label: "羞恥A", value: "shy"},
  233: {category: 6, label: "巨乳", value: "large breasts"},
  234: {category: 6, label: "垂れ乳", value: "hanging breasts"},
  235: {category: 6, label: "爆乳", value: "huge breasts"},
  236: {category: 6, label: "貧乳", value: "small breasts"},
  237: {category: 6, label: "普乳", value: "medium breasts"},
  238: {category: 6, label: "無乳", value: "flat chest"},
  239: {category: 7, label: "アイコンタクト", value: "eye contact"},
  240: {category: 7, label: "こちらを見ている", value: "looking at viewer"},
  241: {category: 7, label: "よそ見している", value: "looking away"},
  242: {category: 7, label: "遠くを見る", value: "looking afar"},
  243: {category: 7, label: "横を見ている", value: "looking to the side"},
  244: {category: 7, label: "外側を見ている", value: "looking outside"},
  245: {category: 7, label: "眼鏡越しに見ている", value: "looking over eyewear"},
  246: {category: 7, label: "胸を見ている", value: "looking at breasts"},
  247: {category: 7, label: "鏡を見ている", value: "looking at mirror"},
  248: {category: 7, label: "携帯を見ている", value: "looking at phone"},
  249: {category: 7, label: "見下ろしている", value: "looking down"},
  250: {category: 7, label: "見上げている", value: "looking up"},
  251: {category: 7, label: "後ろを向いている", value: "looking back"},
  252: {category: 7, label: "手を見ている", value: "looking at hand"},
  253: {category: 7, label: "足の間から見ている", value: "looking through legs"},
  254: {category: 7, label: "誰かが他の誰かを見ている（一方的に）", value: "looking at another"},
  255: {category: 7, label: "ガマン汁", value: "precum"},
  256: {category: 8, label: "溢れ精液", value: "cumdrip"},
  257: {category: 8, label: "顔射", value: "facial"},
  258: {category: 8, label: "胸射", value: "breast milk"},
  259: {category: 8, label: "口内射精（ごっくん）", value: "cum in mouth"},
  260: {category: 8, label: "射精", value: "ejaculation"},
  261: {category: 8, label: "腟内射精1（中出し）", value: "cum in pussy"},
  262: {category: 8, label: "腟内射精2（中出し）", value: "creampie"},
  263: {category: 9, label: "すじ", value: "cameltoe"},
  264: {category: 9, label: "つけ耳（ウサギ耳等）", value: "fake animal ears"},
  265: {category: 9, label: "パフィーニップル", value: "puffy nipples"},
  266: {category: 9, label: "フタナリ", value: "futanari"},
  267: {category: 9, label: "ボーイッシュ", value: "tomboy"},
  268: {category: 9, label: "ほくろ", value: "mole"},
  269: {category: 9, label: "マニキュア", value: "nail polish"},
  270: {category: 9, label: "レイプ目", value: "empty eyes"},
  271: {category: 9, label: "陰毛", value: "pubic hair"},
  272: {category: 9, label: "褐色", value: "dark skin"},
  273: {category: 9, label: "泣きぼくろ", value: "mole under eye"},
  274: {category: 9, label: "猫しっぽ", value: "cat tail"},
  275: {category: 9, label: "猫耳", value: "cat ears"},
  276: {category: 20, label: "3人", value: "threesome"},
  277: {category: 20, label: "女x人（xを数字に）", value: "xgirl"},
  278: {category: 20, label: "男x人（xを数字に）", value: "xboy"},
  279: {category: 10, label: "NSFW", value: "nsfw"},
  280: {category: 10, label: "ずらし挿入", value: "clothing aside"},
  281: {category: 10, label: "セックス", value: "sex"},
  282: {category: 10, label: "タマ舐め", value: "testicle sucking"},
  283: {category: 10, label: "パイズリ", value: "paizuri"},
  284: {category: 10, label: "パイズリされる竿", value: "breast in 1penis"},
  285: {category: 10, label: "バック", value: "sex from behind"},
  286: {category: 10, label: "フェラチオ", value: "fellatio"},
  287: {category: 10, label: "愛液", value: "love juice"},
  288: {category: 10, label: "駅弁", value: "suspended congress"},
  289: {category: 10, label: "竿召喚", value: "1penis"},
  290: {category: 10, label: "騎乗位", value: "cowgirl position"},
  291: {category: 10, label: "騎乗位", value: "straddling"},
  292: {category: 10, label: "胸からはみ出す竿", value: "glans penis"},
  293: {category: 10, label: "事後、射精直後", value: "after sex"},
  294: {category: 10, label: "自慰（女性）", value: "female masturbation"},
  295: {category: 10, label: "主観視点", value: "pov"},
  296: {category: 10, label: "手コキ", value: "handjob"},
  297: {category: 10, label: "正常位", value: "missionary"},
  298: {category: 10, label: "正常位2", value: "face-to-face recumbent coital position"},
  299: {category: 10, label: "乳揉み", value: "breast grab"},
  300: {category: 10, label: "背面騎乗位", value: "reverse cowgirl position"},
  301: {category: 10, label: "野外露出", value: "public indecency"},
  302: {category: 11, label: "xx歳（xxに数字を入れる）", value: "xx years old"},
  303: {category: 11, label: "エルフ耳", value: "pointy ears"},
  304: {category: 11, label: "スリム", value: "slim"},
  305: {category: 11, label: "スレンダー", value: "slender"},
  306: {category: 11, label: "でか尻1", value: "fat ass"},
  307: {category: 11, label: "でか尻2", value: "wide hips"},
  308: {category: 11, label: "ぽっちゃりした", value: "plump"},
  309: {category: 11, label: "ボテ腹", value: "pregnant"},
  310: {category: 11, label: "むちむち1", value: "curvy"},
  311: {category: 11, label: "むちむち2", value: "plump"},
  312: {category: 11, label: "やせた", value: "skinny"},
  313: {category: 11, label: "巨乳でか尻", value: "thicc"},
  314: {category: 11, label: "腹筋（0.75ぐらいまで落とさないとマッチョすぎる）", value: "abs"},
  315: {category: 11, label: "肋骨", value: "ribs"},
  316: {category: 12, label: "SDキャラ", value: "chibi"},
  317: {category: 12, label: "ロリ", value: "dwarf"},
  318: {category: 12, label: "身体だけロリ", value: "toddler body"},
  319: {category: 13, label: "あの縦ロール", value: "loose curly hair"},
  320: {category: 13, label: "アフロヘアー", value: "Afro"},
  321: {category: 13, label: "アフロヘアー", value: "Afro hair"},
  322: {category: 13, label: "アフロヘアー", value: "Afro-textured hair"},
  323: {category: 13, label: "アホ毛", value: "ahoge"},
  324: {category: 13, label: "ウェーブヘア", value: "wavy hair"},
  325: {category: 13, label: "うなじ部分の大胆な刈り上げ", value: "nupe undercut"},
  326: {category: 13, label: "オールバック", value: "slicked back hairstyle"},
  327: {category: 13, label: "おかっぱ（ボブ）", value: "bob cut"},
  328: {category: 13, label: "おだんごヘア", value: "hair bun"},
  329: {category: 13, label: "お団子", value: "bun hair"},
  330: {category: 13, label: "がっつり毛を巻くパーマ", value: "curly hair"},
  331: {category: 13, label: "くせっ毛（モジャ）", value: "messy hair"},
  332: {category: 13, label: "サイドテール", value: "side ponytail"},
  333: {category: 13, label: "サイドテール（左側）", value: "side ponytail of left"},
  334: {category: 13, label: "ショートヘア", value: "short hair"},
  335: {category: 13, label: "ショートボブ", value: "short bob cut"},
  336: {category: 13, label: "ストレートパーマ", value: "straight perm"},
  337: {category: 13, label: "セミロング", value: "medium hair"},
  338: {category: 13, label: "センター分け", value: "parted bangs"},
  339: {category: 13, label: "ちょろっとしたふたつ結び", value: "pig tails hair"},
  340: {category: 13, label: "ちょろっとしたふたつ結び", value: "piggy tails hair"},
  341: {category: 13, label: "ツインテール", value: "twintails"},
  342: {category: 13, label: "ツーサイドアップ", value: "two side up"},
  343: {category: 13, label: "ツーブロック", value: "shaved sides"},
  344: {category: 13, label: "デコ出し", value: "forehead"},
  345: {category: 13, label: "ドレッドヘア", value: "dreadlocks hair"},
  346: {category: 13, label: "パーマ", value: "perm"},
  347: {category: 13, label: "ぱっつん", value: "blunt bangs"},
  348: {category: 13, label: "フランスの三つ編み", value: "french braid"},
  349: {category: 13, label: "ボウルカット", value: "bowl cut"},
  350: {category: 13, label: "ポニーテール", value: "ponytail"},
  351: {category: 13, label: "メカクレ", value: "hair over eyes"},
  352: {category: 13, label: "モヒカン", value: "Mohawk haircut"},
  353: {category: 13, label: "ゆるくまとめたおだんご", value: "messy bun hair"},
  354: {category: 13, label: "リーゼント", value: "pompadour"},
  355: {category: 13, label: "ロングヘア", value: "long hair"},
  356: {category: 13, label: "一般的な編み込み", value: "french braid hair"},
  357: {category: 13, label: "外ハネ", value: "flipped hair"},
  358: {category: 13, label: "外巻き髪", value: "curl outward hair"},
  359: {category: 13, label: "襟足を束ねた髪型", value: "updo hair"},
  360: {category: 13, label: "後ろで縛っている長髪", value: "low-tied long hair"},
  361: {category: 13, label: "三つ編み", value: "braid"},
  362: {category: 13, label: "三角おだんご", value: "cone hair bun"},
  363: {category: 13, label: "縦ドリル", value: "smooth curly hair"},
  364: {category: 13, label: "縦ドリル２", value: "special curls hair"},
  365: {category: 13, label: "寝癖", value: "bedhead "},
  366: {category: 13, label: "短いツーブロック", value: "short shaved sides"},
  367: {category: 13, label: "短めのツインテール", value: "short twin tail hair"},
  368: {category: 13, label: "中くらいの髪", value: "semifinal"},
  369: {category: 13, label: "長い乱れ髪", value: "long messy hair"},
  370: {category: 13, label: "内巻き髪", value: "curl inward hair"},
  371: {category: 13, label: "片方分け", value: "swept bangs"},
  372: {category: 13, label: "片目隠れ", value: "hair over one eye"},
  373: {category: 13, label: "坊主頭", value: "buzz cut"},
  374: {category: 13, label: "目のところでばってんの毛", value: "crossed bangs"},
  375: {category: 13, label: "目の間の髪", value: "hair between eyes"},
  376: {category: 13, label: "裏編み込み", value: "dutch braid hair"},
  377: {category: 14, label: "グラデーション", value: "gradient hair"},
  378: {category: 14, label: "ツートン", value: "two-tone hair"},
  379: {category: 14, label: "ピンク髪", value: "pink hair"},
  380: {category: 14, label: "金髪", value: "blonde hair"},
  381: {category: 14, label: "銀髪", value: "grey hair"},
  382: {category: 14, label: "黒髪", value: "black hair"},
  383: {category: 14, label: "紫髪", value: "purple hair"},
  384: {category: 14, label: "青髪", value: "blue hair"},
  385: {category: 14, label: "青緑髪（アクア）", value: "aqua hair"},
  386: {category: 14, label: "赤髪", value: "red hair"},
  387: {category: 14, label: "茶髪", value: "brown hair"},
  388: {category: 14, label: "白髮", value: "white hair"},
  389: {category: 14, label: "複数色髪", value: "multicolored hair"},
  390: {category: 14, label: "緑髪", value: "green hair"},
  391: {category: 15, label: "ROのアコライト", value: "acolyte"},
  392: {category: 15, label: "Tシャツ", value: "t-shirt"},
  393: {category: 15, label: "アバヤ（イスラム女性の着る全身服）", value: "abaya"},
  394: {category: 15, label: "ウェディングヴェール", value: "wedding veil"},
  395: {category: 15, label: "ウェディングドレス", value: "wedding dress"},
  396: {category: 15, label: "オーバーオール", value: "blue dungarees"},
  397: {category: 15, label: "キョンシー", value: "jiangshi"},
  398: {category: 15, label: "コート", value: "coat"},
  399: {category: 15, label: "ゴスロリ", value: "gothic lolita"},
  400: {category: 15, label: "サンタビキニ", value: "santa bikini"},
  401: {category: 15, label: "シアーメッシュ", value: "sheer mesh tops"},
  402: {category: 15, label: "シスター服セット", value: "black head veil, black scapular, black tunic,"},
  403: {category: 15, label: "スカート", value: "skirt"},
  404: {category: 15, label: "スク水", value: "school swimsuit"},
  405: {category: 15, label: "スパッツ", value: "bike shorts"},
  406: {category: 15, label: "スリングショット水着", value: "slingshot swimsuit"},
  407: {category: 15, label: "セーラー服", value: "serafuku"},
  408: {category: 15, label: "タオル巻き", value: "wrapped a large white towel"},
  409: {category: 15, label: "チャイナドレス（チョンサム）", value: "china cheongsam"},
  410: {category: 15, label: "チャイナ服", value: "china dress"},
  411: {category: 15, label: "ドレス・ワンピース", value: "dress"},
  412: {category: 15, label: "ニーソ", value: "thighhighs"},
  413: {category: 15, label: "ぱつぱつのボタンシャツ", value: "button gap"},
  414: {category: 15, label: "ビキニ", value: "bikini"},
  415: {category: 15, label: "ビキニアーマー", value: "ethnic costume-like bikini armor"},
  416: {category: 15, label: "ファンタジーのプリースト", value: "fantasy priest"},
  417: {category: 15, label: "ブーツ", value: "boots"},
  418: {category: 15, label: "フリル付きの服", value: "frilled shirt"},
  419: {category: 15, label: "マイクロビキニ", value: "micro bikini"},
  420: {category: 15, label: "ミニスカート", value: "miniskirt"},
  421: {category: 15, label: "メイドビキニ", value: "maid bikini"},
  422: {category: 15, label: "レオタード", value: "leotard"},
  423: {category: 15, label: "レオタードウェディングドレス", value: "leotard wedding dress"},
  424: {category: 15, label: "レディースの鎧", value: "knightess"},
  425: {category: 15, label: "ロリータファッション", value: "lolita fashion"},
  426: {category: 15, label: "ロングブーツ", value: "knee boots"},
  427: {category: 15, label: "ワンピ水着", value: "one-piece swimsuit"},
  428: {category: 15, label: "下着", value: "underwear"},
  429: {category: 15, label: "鎧スカート（太もも見えるやつ）", value: "armored dress"},
  430: {category: 15, label: "学ラン", value: "gakuran"},
  431: {category: 15, label: "宮廷衣装", value: "otokoyaku"},
  432: {category: 15, label: "競泳水着", value: "competition swimsuit"},
  433: {category: 15, label: "軍服", value: "military jacket"},
  434: {category: 15, label: "肩出し", value: "bare shoulders"},
  435: {category: 15, label: "修道女", value: "nun"},
  436: {category: 15, label: "水着", value: "swimsuit"},
  437: {category: 15, label: "制服", value: "school uniform"},
  438: {category: 15, label: "前掛けやふんどしみたいな服", value: "pelvic curtain"},
  439: {category: 15, label: "全裸", value: "completely nude"},
  440: {category: 15, label: "体育用ジャージ", value: "tracksuit"},
  441: {category: 15, label: "体操着", value: "student training wear"},
  442: {category: 15, label: "着物", value: "kimono"},
  443: {category: 15, label: "長袖", value: "long sleeves"},
  444: {category: 15, label: "背中が見えるドレス", value: "backless dress"},
  445: {category: 15, label: "晩餐会の礼服", value: "ball gown"},
  446: {category: 15, label: "浴衣", value: "yukata"},
  447: {category: 15, label: "裸", value: "nude"},
  448: {category: 15, label: "裸xxx（xxxを服装にする。apronとかcoatとか）", value: "naked xxx"},
  449: {category: 15, label: "巫女", value: "miko"},
  450: {category: 16, label: "ヴィクトリア調", value: "victorian"},
  451: {category: 16, label: "ウサ耳", value: "bunny ears"},
  452: {category: 16, label: "カーディガン", value: "cardigan"},
  453: {category: 16, label: "コサック帽", value: "soviet ushanka hat"},
  454: {category: 16, label: "タトゥー（裸だと淫紋になりやすい）", value: "crotch tattoo"},
  455: {category: 16, label: "チョーカー", value: "choker"},
  456: {category: 16, label: "はだけている状態", value: "open clothes"},
  457: {category: 16, label: "パンスト", value: "pantyhose"},
  458: {category: 16, label: "パンツ見せ", value: "panty peek"},
  459: {category: 16, label: "ぶかぶかの服", value: "oversized clothes"},
  460: {category: 16, label: "プリーツスカート", value: "pleated skirt"},
  461: {category: 16, label: "フリル", value: "frilled"},
  462: {category: 16, label: "ヘアリボン", value: "hair bow"},
  463: {category: 16, label: "ボタンを外す", value: "unbuttoned"},
  464: {category: 16, label: "マスク", value: "mask"},
  465: {category: 16, label: "リボン", value: "ribbon"},
  466: {category: 16, label: "横乳", value: "sideboob"},
  467: {category: 16, label: "下乳", value: "underboob"},
  468: {category: 16, label: "官帽", value: "peaked cap"},
  469: {category: 16, label: "手袋", value: "gloves"},
  470: {category: 16, label: "首巻きスカーフ", value: "ascot"},
  471: {category: 16, label: "首輪", value: "collar"},
  472: {category: 16, label: "絶対領域（ニーハイ＋あふれる太もも）", value: "zettai ryouiki"},
  473: {category: 16, label: "長手袋", value: "arm cover"},
  474: {category: 16, label: "髪留め", value: "barrette"},
  475: {category: 16, label: "紐リボン", value: "neck ribbon"},
  476: {category: 16, label: "帽子", value: "hat"},
  477: {category: 16, label: "目隠し", value: "covering eyes"},
  478: {category: 16, label: "裸足", value: "barefoot"},
  479: {category: 17, label: "アカメ", value: "red eyes"},
  480: {category: 17, label: "オッドアイ", value: "heterochromia"},
  481: {category: 17, label: "グラデーションアイ", value: "gradient eyes"},
  482: {category: 17, label: "ピンク目", value: "pink eyes"},
  483: {category: 17, label: "金眼", value: "yellow eyes"},
  484: {category: 17, label: "銀目", value: "grey eyes"},
  485: {category: 17, label: "黒目", value: "black eyes"},
  486: {category: 17, label: "紫目", value: "purple eyes"},
  487: {category: 17, label: "翠眼（緑）", value: "green eyes"},
  488: {category: 17, label: "青緑眼", value: "aqua eyes"},
  489: {category: 17, label: "茶目", value: "brown eyes"},
  490: {category: 17, label: "白眼", value: "white eyes"},
  491: {category: 17, label: "碧眼（青）", value: "blue eyes"},
}
